language: node_js
sudo: required
node_js:
   - "11"

before_script:
   - "sudo apt-get update && sudo apt-get install -y nginx make"

script: # the build step
   - make

after_script:
   - make clean
